---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list:
  - recipe[apt]
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
  run_list:
  - recipe[apt]

suites:
- name: mongo
  run_list:
  - recipe[razor]
  attributes: {}
- name: postgres
  run_list:
  - recipe[razor]
  attributes:
    razor:
      persist_mode: postgres
      app:
        git_rev: 778e87e294159fd427ce3b526b251e78a3654a72
    postgresql:
      password:
        postgres: razor
- name: lwrps
  run_list:
  - recipe[test::lwrps]
